//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProJect02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao
    {
        public int MaBaoCao { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<int> MaChuong { get; set; }
        public Nullable<int> MaTruyen { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayBaoCao { get; set; }
        public string TrangThaiXuLy { get; set; }
    }
}
