//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProJect02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int MaBinhLuan { get; set; }
        public Nullable<int> MaChuong { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public string NoiDungBinhLuan { get; set; }
        public Nullable<System.DateTime> NgayBinhLuan { get; set; }
        public string TrangThai { get; set; }
    }
}
