//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProJect02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int MaThongBao { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public string NoiDungThongBao { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<bool> DaDoc { get; set; }
    }
}
