//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProJect02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truyen
    {
        public int MaTruyen { get; set; }
        public string TenTruyen { get; set; }
        public string TacGia { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> LuotXem { get; set; }
    }
}
